#!/usr/bin/python3
from factoring_func import factoring
import sys
import time

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Error")
        sys.exit(1)
    arg = sys.argv[1]

    start_time = time.time()

    try:
        with open(arg, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(arg + " file not found")
    except PermissionError:
        print("permission denied")
    except Exception as err:
        print(f"unknown Error: {err}")
    finally:
        for line in lines:
            num = int(line.strip())
            factoring(num)
        if time.time() - start_time > 5:
            print("Time limit exceeded")


